# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-prompt"
gem 'games_dice'
gem 'tty-font'
gem 'colorize'
gem 'rspec'
gem "pastel"